strictness: high
doc-warnings: true
test-warnings: false
autodetect: true
member-warnings: false

pep257:
  disable:
    # Disable mutually exclusive class-docstrings should have leading new line (clash)
    - D203
    - D212

pylint:
    # Pylint run through dedicated plugin rather than via prospector.
    run: false
