language: python

jobs:
  include:
    # ==== Linux ====
    - name: "Linux Python 3.9.0 build"
      os: linux
      dist: focal
      python: 3.9
    # ==== Windows ====
    - name: "Windows Python 3.9.0 build"
      os: windows
      language: shell  # Python isn't supported directly in Travis Windows
      before_install:
        - choco install python --version 3.9.0
        - python --version
        - pip install --upgrade --user pip
        - pip install --upgrade --user pytest
        - pip install --user coverage
      env: PATH=/c/Python39:/c/Python39/Scripts:$PATH

before_install:
  - python --version
  - pip install --upgrade pip
  - pip install --upgrade pytest
  - pip install coverage

install:
  - curl -LO https://github.com/FortAwesome/Font-Awesome/releases/download/5.15.1/fontawesome-free-5.15.1-web.zip
  - 7z e -y -osrc/uosinterface/webapp/static/lib/FontAwesome fontawesome-free-5.15.1-web.zip
  - pip install --requirement resources/requirements.txt

script:
  - python -m pytest src/tests/
