language: python

dist: focal

jobs:
  include:
    # ==== Linux ====
    - name: "Linux 3.9.0 build"
      python: 3.9
    # ==== Windows ====
    - name: "Windows 3.9.0 build"
      os: windows
      language: shell  # Python isn't supported directly in Travis Windows
      before_install:
        - choco install python --version 3.9.0
        - python --version
        - pip install --upgrade --user pip
        - pip install --upgrade --user pytest
        - pip install --user coverage
      env: PATH=/c/Python39:/c/Python39/Scripts:$PATH

before_install:
  - python --version
  - pip install --upgrade pip
  - pip install --upgrade pytest
  - pip install coverage

install:
  - pip install --requirement resources/requirements.txt

script:
  pytest src/tests/
