language: python
python:
  - 3.7
  - 3.8
  - 3.9

env:
  SERVER=TRAVIS

before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install -U coverage

install:
  - pip install -r resources/requirements.txt

script:
  pytest src/tests/
